# Generated by Django 6.0.3 on 2026-03-15 00:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0002_analysissession_legacy_session_id_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenceBatchSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('converged', 'Converged'), ('terminated', 'Terminated')], default='active', max_length=20)),
                ('batch_size', models.PositiveIntegerField(default=5)),
                ('batch_index', models.PositiveIntegerField(default=1)),
                ('swipe_count', models.PositiveIntegerField(default=0)),
                ('seed_image_ids', models.JSONField(default=list)),
                ('liked_image_ids', models.JSONField(default=list)),
                ('disliked_image_ids', models.JSONField(default=list)),
                ('shown_image_ids', models.JSONField(default=list)),
                ('current_batch_ids', models.JSONField(default=list)),
                ('preference_vector', models.JSONField(blank=True, null=True)),
                ('prev_preference_vector', models.JSONField(blank=True, null=True)),
                ('baseline_similarity', models.FloatField(default=0.0)),
                ('pref_change', models.FloatField(default=1.0)),
                ('stability_score', models.FloatField(default=0.0)),
                ('coherence_score', models.FloatField(default=0.0)),
                ('recent_coherence_score', models.FloatField(default=0.0)),
                ('top_k_density_score', models.FloatField(default=0.0)),
                ('convergence_score', models.FloatField(default=0.0)),
                ('is_converged', models.BooleanField(default=False)),
                ('warning', models.CharField(blank=True, default='', max_length=255)),
                ('terminated_reason', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preference_batch_sessions', to='recommendation.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preference_batch_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
    ]
