# Generated by Django 6.0.3 on 2026-03-15 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0003_preferencebatchsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='hated_building_ids',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='liked_building_ids',
            field=models.JSONField(default=list),
        ),
    ]
