# Generated by Django 6.0.3 on 2026-03-15 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0004_project_hated_building_ids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='final_report',
            field=models.TextField(blank=True, default=''),
        ),
    ]
