# Generated by Django 6.0.3 on 2026-03-15 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0005_project_final_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='analysis_report',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='last_report_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='latest_convergence',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='latest_feedback_summary',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='predicted_building_ids',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(default='draft', max_length=32),
        ),
    ]
